# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-central-1"
  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["273711029273"]
}
